version: "2"
sql:
  - engine: "postgresql"
    queries: "queries"
    schema: "build/schema.sql"
    gen:
      go:
        package: "db"
        out: "."
        emit_pointers_for_null_types: true
        sql_package: "pgx/v5"
       
      
          